Django_new/projets/mpund/mpund/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    url('^admin/', admin.site.urls),
    #url(r'^pesa', include('pesa.urls')),
    url(r'^pesa', include('pesa.urls', namespace='pesa')),
]

Django_new/projets/mpund/pesa/urls.py
from django.contrib import admin
from .views import articlespage, successpage
from django.urls import path
from django.conf.urls import url

from .import views 

app_name = 'pesa'

urlpatterns = [
        url('^$',views.pesa_accueil),
        #url('presentation',views.presentation),
        url('saisiearrivees',views.saisie_arv),
#        url(r'^$',views.contact,name='contact'),
#        url(r'^$',views.articlespage,name='homepage'),
        url(r'^success$',views.successpage,name='successpage'),
      #  url('saisiesarv',views.saisiesarv),
        url('myform',views.withform),
        url('article',views.formodel),
        url('arriveesc',views.saisiearvformodel),
#        path('', views.accueilocr1, name='accueilocr1'),
     #   url(r'^$', views.accueilocr1, name='accueilocr1'),
        path('article/<int:id>', views.lire, name='lire'),
#        url('^$', views.accueilocr1, name='accueilocr1'),
        url('affarvc',views.aff_Arriveesc),
#        url('affarvct',views.aff_Arriveesc_trie),
        url('partants',views.saisiepartformodel),
]

Django_new/projets/mpund/pesa/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Article(models.Model):
    titre = models.CharField(max_length=100)
    auteur = models.CharField(max_length=42)
    slug = models.SlugField(max_length=100)
    contenu = models.TextField(null=True)
    date = models.DateTimeField(default=timezone.now, verbose_name="Date de parution")
    #categorie = models.ForeignKey(Categorie)

    def __str__(self):
        return self.titre


class Arriveesc(models.Model):
    dater = models.CharField(max_length=10)
    jsdater = models.CharField(max_length=2, default=None, null=True, blank=True)
    numr = models.IntegerField()
    nbcr = models.IntegerField(blank=True, null=True)
    noctr = models.BooleanField(default=False)
    paysr = models.CharField(max_length=30)
    viller = models.CharField(max_length=30)
    Hippor = models.CharField(max_length=30, default=None, null=True, blank=True )
    numc = models.IntegerField()
    hdepc = models.CharField(max_length=5)
    nomc = models.CharField(max_length=30, default=None, null=True, blank=True)
    typec = models.CharField(max_length=30)
    prixc = models.IntegerField()
    distc = models.IntegerField()
    nbptsc = models.IntegerField()
    quintc = models.BooleanField(default=False)
    arv1c = models.IntegerField()
    arv2c = models.IntegerField()
    arv3c = models.IntegerField()
    arv4c = models.IntegerField()
    arv5c = models.IntegerField(blank=True, null=True)
    rapms4c = models.DecimalField(max_digits=7, decimal_places=2)
    exaquoarvc = models.BooleanField(default=False)

    def __str__(self):
        return self.dater


class Artileocr1(models.Model):
    titre = models.CharField(max_length=100)
    auteur = models.CharField(max_length=42)
    contenu = models.TextField(null=True)
    date = models.DateTimeField(default = timezone.now, verbose_name="Date de parution")

    class meta:
        verbose_name = "article"
        ordering = ['date']

    def __str__(self):
        """
        Cette methode que nous definirons dans tous les modeles nous permettra de reconnaitre 
        facilement les differents objets que nous traiterons plus tard sans l'administration
        """

        return self.titre


class Categorieocr1(models.Model):
    nom = models.CharField(max_length=30)

    def __str__(self):
        return self.nom 

class Articleocr1(models.Model):
    titre = models.CharField(max_length=100)
    auteur = models.CharField(max_length=42)
    contenu = models.TextField(null=True)
    date = models.DateTimeField(default=timezone.now,verbose_name="Date de parution")
    categorie = models.ForeignKey('Categorieocr1', on_delete=models.CASCADE)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return self.titre



class Partants(models.Model):
    datec = models.CharField(max_length=30)
    numr = models.IntegerField()
    numc = models.IntegerField()
    numch = models.IntegerField()
    nomch =  models.CharField(max_length=30)
    particular1 = models.CharField(max_length = 30, null=True, blank=True)
    particular2 = models.CharField(max_length = 30, null=True, blank=True)
    nomjock = models.CharField(max_length=30)
    redkm = models.CharField(max_length=30, null=True, blank=True) 
    coteavt = models.DecimalField(max_digits=5, decimal_places=1)
    coteapr = models.DecimalField(max_digits=5, decimal_places=1)
    commentapc = models.TextField(null=True)
    rang = models.IntegerField()
    motifrg = models.CharField(max_length=10, null=True, blank=True)

    def __str__(numch):
        return self.numch

Django_new/projets/mpund/pesa/forms.py
from django import forms
from .models import Article, Arriveesc, Partants

class ContactForm(forms.Form) : 
    sujet = forms.CharField(max_length = 100)
    message = forms.CharField(widget=forms.Textarea)
    envoyeur = forms.EmailField(label="Votre adresse mail")
    renvoi = forms.BooleanField(help_text="Cochez si vous souhaitez obtenir une copie du mail envoye.", required=False)

class SaisiesArvForm(forms.Form) : 
    dater = forms.CharField()
    paysr = forms.CharField()
    viller = forms.CharField()
    numr = forms.CharField()
    noctr = forms.BooleanField(required=False)
    numc = forms.CharField()
    quintc = forms.BooleanField(required=False)
    nomc = forms.CharField()
    prixc = forms.CharField()
    nbptsc = forms.CharField()
    typec = forms.CharField()
    distc = forms.CharField()
    hdepc = forms.CharField()
    arv1c = forms.CharField()
    arv2c = forms.CharField()
    arv3c = forms.CharField()
    arv4c = forms.CharField()
    arv5c = forms.CharField()
    rapms4c = forms.CharField()


class MyForm(forms.Form):
     email = forms.EmailField(required = True)
     name = forms.CharField(required = True)

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

class ArriveescForm(forms.ModelForm):
    class Meta:
        model = Arriveesc
        fields = '__all__'


class PartantsForm(forms.ModelForm):
    class Meta:
        model = Partants 
        fields = '__all__'

Django_new/projets/mpund/pesa/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponse,Http404
from pesa.forms import ContactForm, SaisiesArvForm, MyForm, ArticleForm, ArriveescForm, PartantsForm
from pesa.models import Articleocr1, Categorieocr1, Arriveesc, Partants

# Create your views here.

def pesa_accueil(request):
    return HttpResponse("hello World")

#def presentation(request) :
 #   return render(request, "pesa/tpl_accueil.html")

def saisie_arv(request) :
    return render(request, "pesa/tpl_saisie_arv.html")



def contact(request) :
    if request.method == 'POST' : # S'il s'agait d'une requete de type POST
       form = ContactForm(request.POST)    # Nous reprenons les donnees

       if form.is_valid() : # Nous verifions que les donnees envoyees sont valides 

            #Ici nous pouvons traiter les donnees du formulaire 
            sujet = form.cleaned_data['sujet']
            message = form.cleaned_data['message']
            envoyeur = form.cleaned_data['envoyeur']
            renvoi = form.cleaned_data['renvoi']

            # Nous pourrions ici envoyer l'email grâce aux donnees que nous venons de recuperer 

            envoi = True

    else: # Si ce n'est pas du POST, c'est probablement une requete GET
        form = ContactForm()  # Nous creons un formulaire vide 

    return render(request, 'pesa/tpl_contact.html', locals())


def articlespage(request):
    return render(request, 'pesa/home.html')

def successpage(request):
    data = request.POST.get('textbox1')

    context = {'data':data}
    return render(request, 'pesa/successpage.html',context)


def saisiesarv(request) :
    if request.method == 'POST' :
        formsaisiesarv =SaisieAarvForm(request.POST)

        if formsaisiesarv.is_valid() :
            envoi = True 
    else:
       formsaisiesarv = SaisiesArvForm()

    return render(request, 'pesa/form.html', {'form':formsaisiesarv})


def withform(request):
    if (request.method == 'POST'):
         form = MyForm(request.POST)
         if form.is_valid():
             return HttpResponse("You currently filled the form !\n You're %s and your email is %s"
                        %(form.cleaned_data['name'], form.cleaned_data['email']))

    else:
        form = MyForm()
    return render(request, "pesa/form.html", {'form' : form})

def formodel(request):
    if (request.method == 'POST'):
        form = ArticleForm(request.POST)
    else:
       form = ArticleForm()
    return render(request, "pesa/form.html", {'form' : form})


def saisiearvformodel(request):
    if (request.method == 'POST'):
        form = ArriveescForm(request.POST)
        if form.is_valid():
            form.save()
    else:
       form = ArriveescForm()
    return render(request, "pesa/form.html", {'form' : form})


def accueilocr1(request):
    """Afficher tous les artiles de """
    articles = Articleocr1.objects.all() # Nous selectionnons tous nos articles 
    return render(request, "pesa/accueilocr1.html", {'derniers_articles': articles})

#def lire(request, id):
#    """Afficher un article complet """
#    pass # Le code de cette fonction est donné un peu plus loin.

def lire(request, id):
    try:
        article = Articleocr1.objects.get(id=id)
    except Article.DoesNotExist:
        raise Http404

    return render(request, 'pesa/lire.html',{'article' : article})


def aff_Arriveesc(request):
    aff_Arvc = Arriveesc.objects.all()
    for curs_aff_Arvc in aff_Arvc :
        print(curs_aff_Arvc.arv1c)
    return render_to_response("pesa/form.html",{'aff_arvc' : aff_Arvc})

def aff_Arriveesc_trie(request):
    aff_Arvc_trie = Arriveesc.objects.all()
    for c in aff_Arvc_trie :
        liste_ar=[c.arv1c,c.arv2c,c.arv3c,c.arv4c]
        liste_ar.sort()
        print(liste_ar)
        arvt = str(liste_ar[0])+'-'+str(liste_ar[1])+'-'+str(liste_ar[2])+'-'+str(liste_ar[3])
        print(arvt)
    return HttpResponse("arrivee triee")


def saisiepartformodel(request):
    if (request.method == 'POST'):
        formpart = PartantsForm(request.POST)
        if formpart.is_valid():
            formpart.save()
    else:
       formpart = PartantsForm()
    return render(request, "pesa/formpart.html", {'formpart' : formpart})

Django_new/projets/mpund/mpund/templates/pesa/accueilocr1.html
<h1>Bienvenue sur le blog des crêpes bretonnes !</h1>

{% for article in derniers_articles %}

	<div class="article">
		<h3>{{article.titre}}</h3>
		<p>{{ article.contenu|truncatewords_html:80}}</p>
		<p><a href="{% url 'pesa:lire' article.id %} > Lire la suite </a></p>
	</div>

{% empty %}
	<p> Aucun article. </p>
{% endfor %}

Django_new/projets/mpund/mpund/templates/pesa/base.html
<! doctype html>
<html>
	<head>
	</head>
	<body>
		{% block content %}
		<h1>This is the base template.</h1>
		{% endblock %}
	</body>
</html>

Django_new/projets/mpund/mpund/templates/pesa/form.html
{% extends "pesa/base.html" %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit">

</form>
{% endblock %}

Django_new/projets/mpund/mpund/templates/pesa/formpart.html
{% extends "pesa/base.html" %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	{{ formpart.as_p }}
	<input type="submit" value="Submit">

</form>
{% endblock %}

Django_new/projets/mpund/mpund/templates/pesa/home.html
<h1>Articles Pages </h1>

<form method="POST" action={% url 'pesa:successpage' %}>
{% csrf_token %}
Enter your name : <input type = 'text' name='textbox1'/> <br><br>
<input type="submit" name="Submit" />
</form>

Django_new/projets/mpund/mpund/templates/pesa/lire.html
<h1>{{article.titre}} <span class="small">dans {{article.categorie.nom}}</span></h1>
<p class="infos">Rédigé par {{article.auteur}}, e {{article.date|date:"DATE_FORMAT"}}</p>
<div class="contenu"> {{article.contenu|linebreaks}}</div>

Django_new/projets/mpund/mpund/templates/pesa/successpage.html
<h1> Success page</h1>
<p> You have successfully entered in the information </p>
<p> The name you entered was {{data}}</p>

Django_new/projets/mpund/mpund/templates/pesa/tpl_accueil.html
  <!doctype html>
  <html>
     <head>
     </head>
     <body>
         <h1>Template page de presentation !  </h1>
     </body>
 </html>

Django_new/projets/mpund/mpund/templates/pesa/tpl_contact.html
{% if envoi %} Votre message a bien ete envoye ! {% endif %}

<form action={% url 'pesa:contact' %}  method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit" />
</form>

Django_new/projets/mpund/mpund/templates/pesa/tpl_saisie_arv.html
<!doctype html>
<html>
	<head>
	</head>
	<body>
		<form method="post">
			<label for="date_r"> Date : </label><input type="date" name="date_r" id="date_r" />
			<br>
			<br>
			<label for="pays_r"> Pays : </label>
			<select name="pays_r" id="pays_r">
				<option value="france">FRANCE</option>
				<option value="Allemagne">ALLEMAGNE</option>
			</select>

			<label for="ville_r"> Ville : </label><input type="text" name="ville_r" id="ville_r" />
			<br>
			<br>
			<label for="hippod_r"> Hippodrome : </label><input type="text" name="hippod_r" id="hippod_r" />
			<label for="pist_p"> Plat : </label><input type="checkbox" name="pist_p" id="pist_p" />
			<label for="pist_a"> Attele : </label><input type="checkbox" name="pist_a" id="pist_a" />
			<label for="pist_o"> Obstacle : </label><input type="checkbox" name="pist_o" id="pist_o" />
			<br>
			<br>
			<label for="num_r"> Num Réunion : </label><input type="number" min="1" max="10" name="num_r" id="num_r" />			
			<label for="noct_r"> Nocturne : </label><input type="radio" name="noct_r" id="noct_r" /> 	
			<br>
			<br>		
			<label for="num_c"> Num Course : </label><input type="number" min="1" max="20" name="num_c" id="num_c" />
			<label for="nom_c"> Nom Course :  </label><input type="text" name="nom_c" id="nom_c" />
			<label for="prix_c"> Prix : </label><input type="text" name="prix_c" id="prix_c" />
			<label for="nbpart_c"> Nb Partants : </label><input type="number" min="2" max="50" name="nbpart_c" id="nbpart_c" /> 
			<br>
			<br>
			<label for="type_c"> Type Course : </label><input type="text" name="type_c" id="type_c" />
			<label for="dist_c"> Distance : </label><input type="text" name="dist_c" id="dist_c" />
			<br>
			<br>
			<label for="depart_c"> Heure Départ : </label><input type="text" name="depart_c" id="depart_c" />
			<br>
			<br>
			<label for="arriv_1">  1er : </label><input type ="number" min="1" max="50" name="arriv_1" id="arriv_1" />
			<label for="arriv_2">  2ème : </label><input type ="number" min="1" max="50" name="arriv_2" id="arriv_2" />
			<label for="arriv_3">  3ème : </label><input type ="number" min="1" max="50" name="arriv_3" id="arriv_3" />
			<label for="arriv_4">  4ème : </label><input type ="number" min="1" max="50" name="arriv_4" id="arriv_4" />
			<label for="arriv_5">  5ème : </label><input type ="number" min="1" max="50" name="arriv_5" id="arriv_5" />
			<br>
			<br>
			<label for="rap_m4" > Rap Multi4 : </label><input type="text" name="rap_m4" id="rap_m4" />

		</form>
	</body> 
</html>